server:
  Address: 127.0.0.1:8080
  ServerAgent: gtoken-demo
  LogPath: ./logs

gToken:
  # 缓存模式 1 gcache 2 gredis 3 gfile
  CacheMode: 2
  # 是否支持多端登录
  MultiLogin: true
  # Token加密key
  EncryptKey: "koi29a83idakguqjq29asd9asd8a7jhq"
  # 排除拦截的地址
  AuthExcludePaths:
    - "/user/info"

# Redis 配置
redis:
  default:
    address: 192.168.19.105:6378
    db: 0
    pass: "root"
