server:
  Address: 127.0.0.1:8083
  ServerAgent: gtoken-demo
  LogPath: ./logs

gToken:
  # 缓存模式 1 gcache 2 gredis 3 gfile
  CacheMode: 3
  # 是否支持多端登录
  MultiLogin: true
  # Token加密key
  EncryptKey: "koi29a83idakguqjq29asd9asd8a7jhq"
  AuthExcludePaths: ["/user/info", "/system/user/info"]

# Redis 配置
redis:
  default:
    address: 127.0.0.1:6379
    db: 0
    pass: demo123
